export const GET_BONUS_LIST = 'GET_BONUS_LIST';
export const GET_BONUS_LIST_SUCCESS = 'GET_BONUS_LIST_SUCCESS';
export const GET_BONUS_LIST_FAILURE = 'GET_BONUS_LIST_FAILURE';

export const ADD_BONUS = 'ADD_BONUS';
export const ADD_BONUS_SUCCESS = 'ADD_BONUS_SUCCESS';
export const ADD_BONUS_FAILURE = 'ADD_BONUS_FAILURE';